# Lets create this website!

# Name of website
title: O. Batuhan Erkat
# Your name to show in the footer
author: O. Batuhan Erkat

# Site description
description: This is my personal webpage
# baseurl: ""
url: ""
# Twitter
twitter_username: batuhanerkat

# Theme for the website
theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-feed


